var questionaire = [
  {
    timeQuestion: "5000",
    questionnumber: "1",
    questionquiz: "What is Javascript?",
    option1: "It is a styling langauge",
    option2: "it is a HTML Language",
    option3: "It is a text-based Programming Langauge for the Web",
    option4: "It is a structured Programming Langauge1",
    answer: "option3",
  },
  {
    timeQuestion: "3000",
    questionnumber: "2",
    questionquiz: "What is WWW, World Wide Web?",
    option1: "It is a combination of all resources and users on the internet",
    option2: "it is a programming language",
    option3: "It is an editor to program computers",
    option4: "It is an App to download",
    answer: "option1",
  },
  {
    timeQuestion: "6000",
    questionnumber: "3",
    questionquiz: "What is Artificial Intelligence",
    option1: "It is a programming language",
    option2: "it is the simulation of human intelligence in computers",
    option3: "It is a method of computing",
    option4: "It is an algorithm",
    answer: "option2",
  },
  {
    timeQuestion: "4000",
    questionnumber: "4",
    questionquiz: "What is an Algorithm",
    option1: "It is a styling language",
    option2: "it is a HTML Language4",
    option3: "It is a Program Langauge for the Web4",
    option4:
      "It is a set of rules to be followed in calculations to solve problems",
    answer: "option4",
  },
  {
    timeQuestion: "4000",
    questionnumber: "5",
    questionquiz: "What is Coding",
    option1: "It is a method to translate computer programs",
    option2:
      "it is a process of using a programming language to create computer programs",
    option3: "It is a system to fix computers",
    option4: "It is the internet",
    answer: "option2",
  },
];
